### ISSUE TITLE
Update links in README.md

### ISSUE THREAD

**Issue by krucios** [krucios/Marsfinder_FW#5]
Some of links are broken.
It's needed to fix them (find new links to related documents).

**Comment by zatirka** [comment]
I'm not sure, what the chassis looks like. May  be like this: https://ru.aliexpress.com/item/4-Wheeled-Robot-Smart-Car-Chassis-Kit-Speed-Encoder-for-Arduino/32838085942.html?spm=a2g0v.search0104.3.42.1565651c2tZBym&ws_ab_test=searchweb0_0,searchweb201602_4_10152_10151_10065_10344_10068_5722815_10342_10343_10340_5722915_10341_5711416_5722615_10696_10084_10083_10618_10307_5722715_10059_100031_10103_5711515_10624_10623_10622_5722515_10621_10620_10125,searchweb201603_1,ppcSwitch_2&algo_expid=e94aa284-761c-4896-9e5c-b7e7a4102b12-6&algo_pvid=e94aa284-761c-4896-9e5c-b7e7a4102b12&priceBeautifyAB=0

**Comment by zatirka** [comment]
Job is done

**Comment by krucios** [comment]
Yes, you're right!
Could you please put this link into README.md?

**Comment by zatirka** [comment]
all links have been checked and added a new valide links instead broken links
