### ISSUE TITLE
Add retcode into message on failed selftest

### ISSUE THREAD

**Issue by krucios** [krucios/Marsfinder_FW#6]
In main.c there are several TODOs (lines 116 and137).
This TODOs should be replaced with new lines of code 😉 

Right now the `mavlink_msg_statustext_pack` accepts string literal as a message, but it's better to put an error code into this message (obtained from `mpu6050_selfTest` function).

Here is the step-by-step guide:
- [x] store a return value of `mpu6050_selfTest` into a variable.
- [x] compare this value with 0 (0 - OK status, not 0 - FAIL status).
- [x] prepare a string message with this return code.
- [x] put this string into `mavlink_msg_statustext_pack` function.

**Comment by zatirka** [comment]
Sorry, what do you mean when you say TODO. I don't understand this abriviation (TODO). Сan you explain me?

**Comment by zatirka** [comment]
And I also don't understand retcode. What is this?

**Comment by krucios** [comment]
"To do" list, i.e., list of things that need to be done. Just to mark things that should be done in future.

**Comment by krucios** [comment]
Retcode - return code. It is a value that is returned from a function.
Usually, if the function returns 0 it means that this function completed without errors. Otherwise, if a retcode is not equal to 0 it means that the function completed with an error. The retcode value can help programmers to understand what kind of error is happened.
For example:
0 - no error
1 - wrong address
2 - wrong data
3 - motors are disabled
4 - power bank is empty
and so on

**Comment by zatirka** [comment]
Added "RETCODE" into the Self Test mesagge
